'use client'
import Link from 'next/link'

const report = {
  student: 'Emma T.',
  date: '27 March 2025',
  assessor: 'Reading Buddy AI',
  grade: 'Year 3',
  readingLevel: 'Stage 4 (above average)',
  fluencyScore: 87,
  comprehensionScore: 74,
  vocabularyScore: 81,
  overallScore: 81,
  strengths: ['Strong phonics foundation', 'Above-average reading speed (112 WPM)', 'Good initial comprehension on familiar topics'],
  gaps: ['Inference questions on unfamiliar topics', 'Multi-syllable word decoding', 'Retelling with full detail'],
  plan: [
    { week: 'Week 1–2', focus: 'Inference building exercises with non-fiction texts' },
    { week: 'Week 3–4', focus: 'Multi-syllable decoding — targeted word lists' },
    { week: 'Week 5–6', focus: 'Oral retelling practice with structured scaffolding' },
    { week: 'Week 7–8', focus: 'Re-assessment + parent/teacher review' },
  ],
  recommendation: 'Emma is reading above the expected level for Year 3. Her primary area for growth is inferential comprehension. With 6–8 weeks of targeted coaching, she is expected to reach the top 20% of her cohort.',
}

function ScoreBar({ score, label }: { score: number; label: string }) {
  return (
    <div style={{ marginBottom: '1rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.35rem' }}>
        <span style={{ fontSize: '0.9rem', fontWeight: 500 }}>{label}</span>
        <span style={{ fontSize: '0.9rem', fontWeight: 700, color: 'var(--sage)' }}>{score}/100</span>
      </div>
      <div style={{ height: 8, background: 'var(--border)', borderRadius: 50 }}>
        <div style={{ height: 8, background: 'var(--sage)', borderRadius: 50, width: `${score}%`, transition: 'width 1s ease' }} />
      </div>
    </div>
  )
}

export default function Report() {
  return (
    <>
      <nav className="nav">
        <div className="nav-logo"><Link href="/">📚 Reading Buddy</Link></div>
        <div className="nav-links">
          <Link href="/pricing">Pricing</Link>
          <Link href="/start" className="btn-primary">Get My Report</Link>
        </div>
      </nav>

      <div style={{ background: 'var(--cream)', borderBottom: '1px solid var(--border)', padding: '1.5rem 2rem', textAlign: 'center' }}>
        <p style={{ fontSize: '0.85rem', color: 'var(--mid)' }}>
          📄 This is a <strong>sample report</strong> showing real output format. Your child's report will be generated after their first session.
        </p>
      </div>

      <main style={{ maxWidth: 800, margin: '0 auto', padding: '4rem 2rem' }}>
        {/* Report header */}
        <div style={{ borderBottom: '3px solid var(--sage)', paddingBottom: '2rem', marginBottom: '2.5rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '1rem' }}>
            <div>
              <div style={{ fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.1em', color: 'var(--sage)', fontWeight: 600, marginBottom: '0.5rem' }}>Reading Buddy AI Assessment Report</div>
              <h1 style={{ fontFamily: 'Fraunces, serif', fontSize: '2rem', marginBottom: '0.25rem' }}>Student: {report.student}</h1>
              <p style={{ color: 'var(--mid)', fontSize: '0.9rem' }}>{report.grade} · {report.date} · Generated by {report.assessor}</p>
            </div>
            <div style={{ background: 'var(--sage)', color: 'white', borderRadius: 16, padding: '1.25rem 2rem', textAlign: 'center' }}>
              <div style={{ fontSize: '2.5rem', fontFamily: 'Fraunces, serif', fontWeight: 900 }}>{report.overallScore}</div>
              <div style={{ fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.08em' }}>Overall Score</div>
            </div>
          </div>
        </div>

        {/* Reading Level */}
        <div style={{ background: '#e8f5ee', border: '1px solid #b8dfc5', borderRadius: 12, padding: '1.5rem', marginBottom: '2rem' }}>
          <p style={{ fontSize: '0.8rem', color: 'var(--sage)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: '0.4rem' }}>Reading Level</p>
          <p style={{ fontFamily: 'Fraunces, serif', fontSize: '1.4rem', fontWeight: 700 }}>{report.readingLevel}</p>
        </div>

        {/* Score breakdown */}
        <div style={{ border: '1px solid var(--border)', borderRadius: 16, padding: '2rem', marginBottom: '2rem' }}>
          <h2 style={{ fontFamily: 'Fraunces, serif', fontSize: '1.3rem', marginBottom: '1.5rem' }}>Score Breakdown</h2>
          <ScoreBar score={report.fluencyScore} label="Reading Fluency" />
          <ScoreBar score={report.comprehensionScore} label="Comprehension" />
          <ScoreBar score={report.vocabularyScore} label="Vocabulary" />
        </div>

        {/* Strengths and gaps */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(280px,1fr))', gap: '1.5rem', marginBottom: '2rem' }}>
          <div style={{ border: '1px solid var(--border)', borderRadius: 16, padding: '2rem' }}>
            <h2 style={{ fontFamily: 'Fraunces, serif', fontSize: '1.2rem', marginBottom: '1rem', color: 'var(--sage)' }}>✓ Strengths</h2>
            <ul style={{ listStyle: 'none' }}>
              {report.strengths.map(s => <li key={s} style={{ padding: '0.4rem 0', fontSize: '0.9rem', borderBottom: '1px solid var(--border)' }}>{s}</li>)}
            </ul>
          </div>
          <div style={{ border: '1px solid var(--border)', borderRadius: 16, padding: '2rem' }}>
            <h2 style={{ fontFamily: 'Fraunces, serif', fontSize: '1.2rem', marginBottom: '1rem', color: '#c4851a' }}>⚠ Areas for Growth</h2>
            <ul style={{ listStyle: 'none' }}>
              {report.gaps.map(g => <li key={g} style={{ padding: '0.4rem 0', fontSize: '0.9rem', borderBottom: '1px solid var(--border)' }}>{g}</li>)}
            </ul>
          </div>
        </div>

        {/* Improvement plan */}
        <div style={{ border: '1px solid var(--border)', borderRadius: 16, padding: '2rem', marginBottom: '2rem' }}>
          <h2 style={{ fontFamily: 'Fraunces, serif', fontSize: '1.2rem', marginBottom: '1.5rem' }}>8-Week Improvement Plan</h2>
          {report.plan.map(p => (
            <div key={p.week} style={{ display: 'flex', gap: '1rem', padding: '0.75rem 0', borderBottom: '1px solid var(--border)', alignItems: 'flex-start' }}>
              <span style={{ background: 'var(--sage)', color: 'white', borderRadius: 50, width: 28, height: 28, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.7rem', flexShrink: 0 }}>→</span>
              <div>
                <strong style={{ fontSize: '0.85rem', color: 'var(--sage)' }}>{p.week}</strong>
                <p style={{ fontSize: '0.9rem', color: 'var(--charcoal)', marginTop: '0.2rem' }}>{p.focus}</p>
              </div>
            </div>
          ))}
        </div>

        {/* Recommendation */}
        <div style={{ background: 'var(--charcoal)', color: 'white', borderRadius: 16, padding: '2rem', marginBottom: '3rem' }}>
          <h2 style={{ fontFamily: 'Fraunces, serif', fontSize: '1.2rem', marginBottom: '1rem' }}>Professional Recommendation</h2>
          <p style={{ lineHeight: 1.7, color: 'rgba(255,255,255,0.85)' }}>{report.recommendation}</p>
        </div>

        <div style={{ textAlign: 'center' }}>
          <p style={{ color: 'var(--mid)', marginBottom: '1.5rem' }}>Get a report like this for your child — free.</p>
          <Link href="/start" className="btn-primary" style={{ fontSize: '1.05rem', padding: '0.9rem 2.5rem' }}>Start Free Assessment →</Link>
        </div>
      </main>
      <footer><p>© 2025 Tech 4 Humanity Pty Ltd</p></footer>
    </>
  )
}
